# Defines a default set of lint rules enforced for
# projects at Google. For details and rationale,
# see https://github.com/dart-lang/pedantic#enabled-lints.
include: package:pedantic/analysis_options.yaml

# For lint rules and documentation, see http://dart-lang.github.io/linter/lints.
# Uncomment to specify additional rules.
linter:
  rules:
    camel_case_types: true
    prefer_single_quotes: false
    omit_local_variable_types: false

analyzer:
  strong-mode:
    implicit-dynamic: false
    # TODO(chandler37): This is just because https://github.com/dart-lang/protobuf/issues/390 has not been resolved:
    implicit-casts: true
  exclude:
    - lib/src/generated/**
