name: immaculater_dart
description: Dart-language code encapsulating Immaculater's mergeprotobufs API for reading and writing to-do lists
version: 0.3.0-dev.1
author: 'David L. Chandler <immaculaterhelp@gmail.com>'
homepage: https://github.com/chandler37/immaculater_dart

environment:
  sdk: '>=2.5.0 <3.0.0'

dependencies:
  crypto: ^2.1.3
  http: ^0.12.0+2
  fixnum: ^0.10.9
  meta: ^1.1.7
  protobuf: ^1.0.0

dev_dependencies:
  pedantic: ^1.8.0
  test: ^1.6.0
  mockito: ^4.1.1
