name: immaculater_dart
description: Dart-language code encapsulating Immaculater's mergeprotobuf API and pyatdl.ToDoList protocol
version: 1.0.0
# author: David L. Chandler (chandler37 on github)

environment:
  sdk: '>=2.5.0 <3.0.0'

dependencies:
  crypto: ^2.1.3
  http: ^0.12.0+2
  fixnum: ^0.10.9
  protobuf: ^1.0.0

dev_dependencies:
  pedantic: ^1.8.0
  test: ^1.6.0
  mockito: ^4.1.1
